# Generated by Django 4.2.6 on 2023-11-04 19:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, max_length=250)),
                ('text', wagtail.fields.RichTextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=90, verbose_name='Button Text')),
                ('content', wagtail.fields.StreamField([('headline_text_horizontal_line', wagtail.blocks.StructBlock([('subline', wagtail.blocks.CharBlock(blank=True, form_classname='Subline')), ('heading', wagtail.blocks.CharBlock(blank=True, form_classname='Title')), ('paragraph', wagtail.blocks.RichTextBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text_align', wagtail.blocks.ChoiceBlock(blank=True, choices=[('last', 'Links'), ('first', 'Rechts')], label='Textausrichtung', max_length=20))])), ('company', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock(blank=True, form_classname='Title')), ('paragraph', wagtail.blocks.RichTextBlock(blank=True)), ('button_text', wagtail.blocks.CharBlock(blank=True, form_classname='Button Text')), ('bg_color', wagtail.blocks.ChoiceBlock(blank=True, choices=[('bg-body-tertiary', 'Tertiary'), ('Light', 'Dark')], label='Hintergrund Farbe', max_length=20)), ('page_link', wagtail.blocks.PageChooserBlock(help_text='Wählen Sie die verlinkte Seite aus', label='Seiten Verlinkung', required=False))])), ('location', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('titel', wagtail.blocks.CharBlock(label='Titel', max_length=40, required=True)), ('text', wagtail.blocks.TextBlock(label='Textbereich', max_length=200, required=True)), ('button_page', wagtail.blocks.PageChooserBlock(label='Seiten Verlinkung', required=False)), ('cta', wagtail.blocks.CharBlock(label='cta', max_length=40, required=True)), ('color_scheme', wagtail.blocks.ChoiceBlock(blank=True, choices=[('bg-body-tertiary', 'Light'), ('text-bg-dark', 'Dark')], label='Farbschema', max_length=20))])))]))], blank=True, use_json_field=True)),
                ('page_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Seiten Verlinkung')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
