# Generated by Django 4.2.6 on 2023-11-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servidepage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidepage',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Service Pages'},
        ),
    ]
