# Generated by Django 4.2.6 on 2023-11-04 14:11

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_headline_homepage_subline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('marketing_block', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(blank=True, form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock(blank=True))]))], blank=True, use_json_field=True),
        ),
    ]
