# Generated by Django 4.2.6 on 2023-11-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0016_alter_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(blank=True, max_length=90, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Seiten Verlinkung'),
        ),
    ]
