# Generated by Django 4.2 on 2023-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Geben Sie eine externe URL ein, falls erforderlich.', null=True),
        ),
    ]
